project:
  type: website

website:
  title: "Hudson Carbon Lab Manual and Collaboration Field Guide"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - quicklinks.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

