---
title: "Expectations"
---

As a collaborative group, both within and outside of our own organization, it is important to lay out expectations for ourselves in terms of how we work (alone and together). Below is a non-exhaustive list of suggested expectations as a member of our lab at Hudson Carbon.

Trust: Our working together is predicated on mutual trust and understanding of our shared goals. We will work to establish a trusting and trusted working relationship with each other and regarding projects we take on. We will trust each other to share boundaries, goals, and needs.

Communication: Collaborative work, both within Hudson Carbon as collaborating individuals and with other institutions we work with, requires clear, frequent, and straightforward communication. We will work to reduce the frequency of jargon when discussing projects when possible; to educate ourselves and each other on necessary terms and phrases that come up in our work; and to reduce the likelihood of misunderstanding through respectful and open communication about project goals, timelines, and roles. Elizabeth will work to establish a regular, goal-oriented line of communication with each individual Hudson Carbon researcher as well as with the whole group, to ensure that consistent and clear communication occurs as often as needed. As a whole, we will commit to learning communication platforms that will advance our projects and reduce miscommunications (e.g., Slack, Office 365, etc.).

Conflict and Disagreement: It is inevitable in a collaborative work environment, and in research science, for disagreements to arise. As a team we are committed to reducing the likelihood of conflicts and disagreements by practicing communication, but when they do occur we will use respectful language and a problem-solving mindset.

Mutual respect: As a team, we will treat each other with respect and care to foster a positive and supportive work environment. While this environment creation is the primary goal, it is also important to acknowledge that such an environment will benefit the work we are pursuing together: our research will likely be more successful, be pursued with more creativity, and result in productive outcomes.

Work style: Everyone has a different work style, a different suite of particular strengths, and a different personality. By committing to communication, we will identify how we best contribute to the projects we pursue. This is a moving target, but working to identify our strengths and where we need assistance or contributions will result in an ever-improving collaborative research environment at Hudson Carbon.